export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
export const USER_LOADING = 'USER_LOADING';
export const CLEAR_DATA = 'CLEAR_DATA';
export const FETCH_USER_DAILYS = 'FETCH_USER_DAILYS';
export const USER_DAILYS_LOADING = 'USER_DAILYS_LOADING';
